[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "7rppEp63Wc6gyoPEwtaAaqAu3MYwcDNoNor2Ha3izQmQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/superstar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
